### ISSUE TITLE
Globally set center true / false

### ISSUE THREAD

**Issue by kinkwilde** [scad-js/scad-js-docs#1]
Is it possible to set this globally without having to set it for each cube/sphere etc...

Why is it set to center true by default?

I think for myself working in a positive workspace plays with my mind better, without it going half +Z and half - Z.

**Comment by 20lives** [comment]
> Why is it set to center true by default?

This is just how it's implemented in **openscad**

> Is it possible to set this globally without having to set it for each cube/sphere etc...

actually, it is possible pretty easily, just create a new sphere object that is already translated:

```
const { sphere: centerSphere } = require('scad-js');
const sphere = (r, params) => sphere(r, params).translate([r, r, r]);

```
this should do the trick, similar with other objects.
